#!/usr/bin/env python3
"""
================================================================================
C++ REFACTORING SCRIPT (Generated by Google Gemini)
================================================================================

AI CONTEXT / SYSTEM PROMPT RECOVERY:
If you are an AI reading this, this script was built iteratively to refactor a 
C++ codebase using libclang. It enforces strict naming conventions, replaces 
'auto' with explicit types safely, and fixes indentation.

CORE RULES & HEURISTICS:
1. Naming Conventions:
   - Parameters: 'p' prefix (e.g., pValue)
   - Class Members: 'm' prefix
   - Static Class Members: 'ms' prefix
   - Global/Namespace Variables: 'g' (normal), 's' (static), 'c' (const), 'sc' (static const)
   - Local Variables: 'l' (normal), 'ls' (static), 'c' (constexpr or local const), 'sc' (static const)
   - Exclusions: Short math/loop vars (i, j, k, x, y, z, w, h, e, it, id, p).
   - The script strips old prefixes before applying the new ones.

2. 'auto' Keyword Replacement (Smart Merge):
   - Goal: Replace 'auto' while preserving user typedefs (e.g. 'ESFileInfoId' instead of 'unsigned int').
   - Method: It checks if the "canonical" type (deep AST) preserves all identifiers found in the 
     "spelling" type (surface AST). If so, canonical is used to restore missing std:: namespaces.
   - STL Typedef Healing: If canonical destroys a typedef, we fallback to spelling. If the spelling 
     is a generic STL alias (like 'value_type' or 'reference') where the domain typedef is completely 
     lost by libclang, the script ABORTS the replacement and preserves the 'auto' keyword.
   - Exclusions: Keeps 'auto' if the resolved type is > 85 chars, or contains internal 
     STL names ('_Tree', '_List', 'iterator') or lambda parameters ('type-parameter').

3. Safety Mechanisms (Crucial for Qt/C++):
   - Macro Shield: Uses regex to map all `#define` blocks. Blocks any AST modifications inside them.
   - Physical Check: Reads the raw bytes at the Clang-provided offset. If the text does not 
     exactly match the expected variable name (or start with 'auto'), it skips. This prevents 
     corrupting Qt macros like Q_OBJECT or Q_PROPERTY that generate hidden AST nodes.

4. Formatting & Build Context:
   - Parses Visual Studio (.vcxproj) files to extract Include Paths and Preprocessor Defines.
   - Converts leading groups of 4 spaces to 1 tab (--spaces-to-tabs).
   - Supports an exceptions file with wildcards to ignore specific files.

USAGE:
python CodingRules.py <src_dirs...> --vs-dir <path> [--replace-auto] [--spaces-to-tabs]
================================================================================
"""

import os
import argparse
import fnmatch
import re
import logging
import xml.etree.ElementTree as ET
import clang.cindex
from clang.cindex import CursorKind, StorageClass, TokenKind

# Logging configuration
script_dir = os.path.dirname(os.path.abspath(__file__))

class RefactorContext:
    def __init__(self, replace_auto=False):
        self.replace_auto = replace_auto
        self.replacements = {} 
        self.decl_to_new_name = {}
        self.file_contents = {} 
        self.file_macros = {} 
        self.report = []

    def add_replacement(self, filepath, start, end, new_text, desc, content_bytes, old_name_expected):
        filename = os.path.basename(filepath)
        
        # 1. Macro Protection
        if filepath not in self.file_macros:
            pattern = re.compile(br'^[ \t]*#define(?:[^\n]*?\\[ \t]*\r?\n)*[^\n]*', re.MULTILINE)
            self.file_macros[filepath] = [(m.start(), m.end()) for m in pattern.finditer(content_bytes)]
            
        for m_start, m_end in self.file_macros[filepath]:
            if m_start <= start <= m_end:
                logging.debug(f"  [SKIP] [{filename}] Macro definition protection at {start} for '{old_name_expected}'")
                return False

        # 2. Physical Protection
        actual_text = content_bytes[start:end].decode('utf-8', errors='ignore')
        
        if old_name_expected == "auto":
            if not re.match(r'^auto\b', actual_text):
                logging.debug(f"  [SKIP] [{filename}] Physical mismatch at {start}: Found '{actual_text}', Expected starting with 'auto'")
                return False
        else:
            if actual_text != old_name_expected:
                logging.debug(f"  [SKIP] [{filename}] Physical mismatch at {start}: Found '{actual_text}', Expected '{old_name_expected}'")
                return False

        if filepath not in self.replacements:
            self.replacements[filepath] = []
        if not any(r[0] == start for r in self.replacements[filepath]):
            self.replacements[filepath].append((start, end, new_text, desc))
            self.report.append(f"{filename}: {desc}")
            return True
        return False

def extract_from_vcxproj(vs_directory):
    inc, df = [], []
    for root, _, files in os.walk(vs_directory):
        for f in files:
            if f.endswith('.vcxproj'):
                p_dir = os.path.abspath(root)
                try:
                    tree = ET.parse(os.path.join(root, f))
                    ns = {'ns': 'http://schemas.microsoft.com/developer/msbuild/2003'}
                    for it in tree.findall('.//ns:AdditionalIncludeDirectories', ns):
                        if it.text:
                            inc.extend([os.path.normpath(os.path.join(p_dir, p.strip())) for p in it.text.split(';') if p.strip() and '%' not in p])
                    for dt in tree.findall('.//ns:PreprocessorDefinitions', ns):
                        if dt.text:
                            df.extend([d.strip() for d in dt.text.split(';') if d.strip() and '%' not in d])
                except Exception as e:
                    logging.error(f"Error parsing vcxproj {f}: {e}")
    return list(set(inc)), list(set(df))

def load_exceptions(filepath):
    if not os.path.exists(filepath): return set()
    with open(filepath, 'r', encoding='utf-8', errors='surrogateescape') as f:
        return set(line.strip() for line in f if line.strip() and not line.startswith('#'))

def should_exclude(filepath, exceptions):
    fname = os.path.basename(filepath)
    for p in exceptions:
        if fnmatch.fnmatch(fname, p) or fnmatch.fnmatch(filepath, p):
            return True
    return False

def get_files_to_process(directories, exceptions):
    target_files = []
    for directory in directories:
        for root, _, files in os.walk(directory):
            for f in files:
                if f.endswith(('.h', '.cpp')):
                    full_path = os.path.normpath(os.path.join(root, f))
                    if should_exclude(full_path, exceptions):
                        continue
                    target_files.append(os.path.normcase(os.path.abspath(full_path)))
    return list(set(target_files))

def generate_new_name(old_name, prefix, is_param):
    if not old_name or old_name in ['i','j','k','e','x','y','z','w','h','it','id','p'] or len(old_name) < 2:
        return old_name
    if is_param and old_name[0].islower() and old_name[1].isupper():
        return prefix + old_name[1:]
    
    if prefix == 'm' and old_name.startswith('ms') and len(old_name) > 2 and old_name[2].isupper():
        return old_name
        
    if old_name.startswith(prefix) and len(old_name) > len(prefix) and old_name[len(prefix)].isupper():
        return old_name
    
    core = old_name
    for k in ['sc','ms','ls','m','l','p','a','n','b','c','s','g']:
        if core.startswith(k) and len(core) > len(k) and (core[len(k)].isupper() or core[len(k)].isdigit()):
            core = core[len(k):]; break
            
    if core[0].islower(): core = core[0].upper() + core[1:]
    return prefix + core

def get_decl_id(cursor):
    usr = cursor.get_usr()
    return usr if usr else f"{cursor.location.file.name}:{cursor.location.offset}" if cursor.location.file else str(cursor.hash)

def process_cursor(cursor, context, project_dirs):
    if not cursor.location or not cursor.location.file:
        for child in cursor.get_children(): process_cursor(child, context, project_dirs)
        return

    path = os.path.normcase(os.path.abspath(cursor.location.file.name))
    if path not in context.file_contents: return

    content = context.file_contents[path]
    filename = os.path.basename(path)
    prefix = None
    is_var = False

    if cursor.kind == CursorKind.PARM_DECL:
        prefix = 'p'; is_var = True
    elif cursor.kind == CursorKind.FIELD_DECL:
        prefix = 'm'; is_var = True
    elif cursor.kind == CursorKind.VAR_DECL:
        is_var = True
        is_static = (cursor.storage_class == StorageClass.STATIC)
        
        is_const = cursor.type.is_const_qualified()
        is_constexpr = False
        try:
            tokens = list(cursor.get_tokens())
            if any(t.spelling == 'constexpr' for t in tokens):
                is_constexpr = True
                is_const = True
            elif any(t.spelling == 'const' for t in tokens):
                is_const = True
        except:
            pass

        is_member = cursor.semantic_parent and cursor.semantic_parent.kind in [CursorKind.CLASS_DECL, CursorKind.STRUCT_DECL, CursorKind.CLASS_TEMPLATE]
        
        if is_member: 
            prefix = 'ms'
        elif cursor.semantic_parent and cursor.semantic_parent.kind in [CursorKind.TRANSLATION_UNIT, CursorKind.NAMESPACE]:
            prefix = 'sc' if is_const and is_static else 's' if is_static else 'c' if is_const else 'g'
        else: 
            if is_const and is_static: prefix = 'sc'
            elif is_constexpr: prefix = 'c'
            elif is_static: prefix = 'ls'
            else: prefix = 'l'

    if is_var and cursor.spelling:
        old_name = cursor.spelling
        
        # AUTO Replacement
        if context.replace_auto:
            try:
                tokens = list(cursor.get_tokens())
                a_idx = next((i for i, t in enumerate(tokens) if t.spelling == 'auto'), -1)
                
                if a_idx != -1:
                    token_strings = [t.spelling for t in tokens]
                    type_spelling = cursor.type.spelling
                    type_canonical = cursor.type.get_canonical().spelling
                    type_kind = str(cursor.type.kind)
                    logging.debug(f"  [AST-DUMP] [{filename}] Var: '{old_name}' | Tokens: {token_strings} | Spelling: '{type_spelling}' | Canonical: '{type_canonical}' | Kind: {type_kind}")

                    v_idx = next((i for i in range(a_idx+1, len(tokens)) if tokens[i].spelling == old_name), -1)
                    if v_idx != -1:
                        t_spelling = cursor.type.spelling.replace('class ','').replace('struct ','')
                        t_canonical = cursor.type.get_canonical().spelling.replace('class ','').replace('struct ','')
                        
                        # Extract identifiers to check if canonical destroys typedefs
                        identifiers = re.findall(r'\b[a-zA-Z_][a-zA-Z0-9_]*\b', t_spelling)
                        keywords = {'const', 'volatile', 'struct', 'class', 'typename', 'std'}
                        id_set = {ident for ident in identifiers if ident not in keywords}
                        
                        canonical_preserves_typedefs = True
                        for ident in id_set:
                            if ident not in t_canonical:
                                canonical_preserves_typedefs = False
                                break
                        
                        generic_aliases = {'value_type', 'reference', 'pointer', 'type-parameter', 'iterator', 'const_iterator'}
                        is_generic_alias = any(alias in id_set for alias in generic_aliases)
                        
                        # SMART MERGE HEURISTIC
                        if 'auto' in t_spelling:
                            t_resolved = t_canonical
                        elif canonical_preserves_typedefs:
                            t_resolved = t_canonical
                        else:
                            if is_generic_alias:
                                # When canonical destroys typedefs AND surface type is just an alias (like value_type),
                                # it is impossible to reconstruct the domain typedef (e.g. ESFileInfoId).
                                # We must ABORT the replacement and preserve 'auto'.
                                logging.debug(f"  [SKIP] [{filename}] Auto replacement aborted to preserve typedefs (Generic Alias): '{t_spelling}' -> '{t_canonical}'")
                                t_resolved = 'auto'
                            else:
                                t_resolved = t_spelling
                                stl_types = [
                                    'shared_ptr', 'unique_ptr', 'weak_ptr', 'pair', 'tuple', 
                                    'map', 'unordered_map', 'vector', 'list', 'set', 'unordered_set', 
                                    'string', 'wstring', 'mutex', 'shared_mutex', 'lock_guard', 
                                    'unique_lock', 'shared_lock', 'function', 'any', 'optional', 
                                    'variant', 'atomic'
                                ]
                                for stl in stl_types:
                                    t_resolved = re.sub(rf'(?<!:)\b{stl}\b', rf'std::{stl}', t_resolved)

                        is_complex_type = (
                            'iterator' in t_resolved.lower() or 
                            '_Tree' in t_resolved or 
                            '_List' in t_resolved or
                            'type-parameter' in t_resolved or
                            len(t_resolved) > 85
                        )
                        
                        if t_resolved and 'auto' not in t_resolved and 'lambda' not in t_resolved:
                            if not is_complex_type:
                                context.add_replacement(path, tokens[a_idx].extent.start.offset, tokens[v_idx-1].extent.end.offset, t_resolved, f"Auto->{t_resolved}", content, "auto")
                            else:
                                logging.debug(f"  [SKIP] [{filename}] Auto replacement ignored (Type too complex): '{t_resolved}'")
            except Exception as e:
                logging.debug(f"  [AST-ERROR] [{filename}] Failed to parse cursor for '{old_name}': {e}")

        # VARIABLES Renaming
        if not old_name.isupper():
            new_name = generate_new_name(old_name, prefix, cursor.kind == CursorKind.PARM_DECL)
            if old_name != new_name:
                decl_id = get_decl_id(cursor)
                context.decl_to_new_name[decl_id] = new_name
                context.add_replacement(path, cursor.location.offset, cursor.location.offset + len(old_name), new_name, f"Rename {old_name}", content, old_name)

    elif cursor.kind == CursorKind.DECL_REF_EXPR:
        ref = cursor.referenced
        if ref and get_decl_id(ref) in context.decl_to_new_name:
            new_name = context.decl_to_new_name[get_decl_id(ref)]
            context.add_replacement(path, cursor.location.offset, cursor.location.offset + len(cursor.spelling), new_name, "RefUpdate", content, cursor.spelling)

    for child in cursor.get_children(): process_cursor(child, context, project_dirs)

def log_and_apply_replacements(filepath, replacements, content_bytes):
    if not replacements: return content_bytes
    lines = content_bytes.split(b'\n')
    line_offsets = [0]
    for length in (len(line) + 1 for line in lines): line_offsets.append(line_offsets[-1] + length)
    
    replacements.sort(key=lambda x: x[0], reverse=True)
    logged_lines = set()
    for start, end, new_text, desc in replacements:
        line_idx = next((i for i, off in enumerate(line_offsets) if off > start), len(line_offsets) - 1) - 1
        if line_idx not in logged_lines:
            logged_lines.add(line_idx)
            orig = lines[line_idx].decode('utf-8', errors='replace')
            logging.info(f"MODIFIED in {os.path.basename(filepath)} (L{line_idx+1}): {orig.strip()} -> {new_text}")

    for start, end, new_text, _ in replacements:
        content_bytes = content_bytes[:start] + new_text.encode('utf-8') + content_bytes[end:]
    return content_bytes

def convert_spaces_to_tabs(content_bytes, spaces_per_tab=4):
    """Converts groups of spaces to tabs within the leading whitespace block."""
    lines = content_bytes.split(b'\n')
    new_lines = []
    space_block = b' ' * spaces_per_tab
    
    for line in lines:
        match = re.match(br'^([ \t]+)(.*)', line)
        if match:
            leading_ws = match.group(1)
            rest_of_line = match.group(2)
            new_leading_ws = leading_ws.replace(space_block, b'\t')
            new_lines.append(new_leading_ws + rest_of_line)
        else:
            new_lines.append(line)
            
    return b'\n'.join(new_lines)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("directories", nargs='+')
    parser.add_argument("--vs-dir", required=True)
    parser.add_argument("--replace-auto", action="store_true")
    parser.add_argument("--spaces-to-tabs", action="store_true", help="Convert leading spaces to tabs (4 spaces = 1 tab)")
    parser.add_argument("--exceptions", default=os.path.join(script_dir, "CodingRulesExceptions.txt"), help="Path to exceptions file")
    parser.add_argument("--log-file", default=os.path.join(script_dir, "CodingRulesDebug.log"), help="Path to log file")
    args = parser.parse_args()

    # Dynamic logging configuration based on user input
    logging.basicConfig(
        filename=args.log_file, 
        level=logging.DEBUG, 
        format='%(levelname)s - %(message)s',
        filemode='w'
    )

    exceptions = load_exceptions(args.exceptions)
    inc, df = extract_from_vcxproj(args.vs_dir)
    context = RefactorContext(args.replace_auto)
    p_dirs = [os.path.normcase(os.path.abspath(d)) for d in args.directories]
    
    files_to_process = get_files_to_process(args.directories, exceptions)
    for f in files_to_process:
        context.file_contents[f] = open(f, 'rb').read()

    idx = clang.cindex.Index.create()
    c_args = ['-x','c++','-std=c++17','-fms-compatibility','-ferror-limit=0'] + [f'-I{i}' for i in inc] + [f'-D{d}' for d in df]
    
    print(f"Parsing {len(files_to_process)} files...")
    for f in files_to_process:
        tu = idx.parse(f, args=c_args, unsaved_files=[(f, context.file_contents[f])])
        process_cursor(tu.cursor, context, p_dirs)

    print("Applying changes...")
    files_modified = 0
    
    for filepath in files_to_process:
        original_data = context.file_contents[filepath]
        reps = context.replacements.get(filepath, [])
        
        new_data = log_and_apply_replacements(filepath, reps, original_data)
        
        if args.spaces_to_tabs:
            new_data = convert_spaces_to_tabs(new_data)
            
        if new_data != original_data:
            with open(filepath, 'wb') as f: 
                f.write(new_data)
            files_modified += 1
            
    print(f"Success. {files_modified} files updated. {len(context.report)} naming/auto modifications applied.")

if __name__ == "__main__":
    main()